"""Proposal regions are generated by calling this object.

The :meth:`__call__` of this object outputs object detection proposals by
applying estimated bounding box offsets
to a set of anchors.

This class takes parameters to control number of bounding boxes to
pass to NMS and keep after NMS.
If the paramters are negative, it uses all the bounding boxes supplied
or keep all the bounding boxes returned by NMS.

This class is used for Region Proposal Networks introduced in
Faster R-CNN [#]_.

.. [#] Shaoqing Ren, Kaiming He, Ross Girshick, Jian Sun. \
Faster R-CNN: Towards Real-Time Object Detection with \
Region Proposal Networks. NIPS 2015.

Args:
    nms_thresh (float): Threshold value used when calling NMS.
    n_train_pre_nms (int): Number of top scored bounding boxes
        to keep before passing to NMS in train mode.
    n_train_post_nms (int): Number of top scored bounding boxes
        to keep after passing to NMS in train mode.
    n_test_pre_nms (int): Number of top scored bounding boxes
        to keep before passing to NMS in test mode.
    n_test_post_nms (int): Number of top scored bounding boxes
        to keep after passing to NMS in test mode.
    force_cpu_nms (bool): If this is :obj:`True`,
        always use NMS in CPU mode. If :obj:`False`,
        the NMS mode is selected based on the type of inputs.
    min_size (int): A paramter to determine the threshold on
        discarding bounding boxes based on their sizes.

        input should  be ndarray
        Propose RoIs.

        Inputs :obj:`loc, score, anchor` refer to the same anchor when indexed
        by the same index.

        On notations, :math:`R` is the total number of anchors. This is equal
        to product of the height and the width of an image and the number of
        anchor bases per pixel.

        Type of the output is same as the inputs.

        Args:
            loc (array): Predicted offsets and scaling to anchors.
                Its shape is :math:`(R, 4)`.
            score (array): Predicted foreground probability for anchors.
                Its shape is :math:`(R,)`.
            anchor (array): Coordinates of anchors. Its shape is
                :math:`(R, 4)`.
            img_size (tuple of ints): A tuple :obj:`height, width`,
                which contains image size after scaling.
            scale (float): The scaling factor used to scale an image after
                reading it from a file.

        Returns:
            array:
            An array of coordinates of proposal boxes.
            Its shape is :math:`(S, 4)`. :math:`S` is less than
            :obj:`self.n_test_post_nms` in test time and less than
            :obj:`self.n_train_post_nms` in train time. :math:`S` depends on
            the size of the predicted bounding boxes and the number of
            bounding boxes discarded by NMS.

"""

"""Assign ground truth bounding boxes to given RoIs.

The :meth:`__call__` of this class generates training targets
for each object proposal.
This is used to train Faster RCNN [#]_.

.. [#] Shaoqing Ren, Kaiming He, Ross Girshick, Jian Sun. \
Faster R-CNN: Towards Real-Time Object Detection with \
Region Proposal Networks. NIPS 2015.

Args:
    n_sample (int): The number of sampled regions.
    pos_ratio (float): Fraction of regions that is labeled as a
        foreground.
    pos_iou_thresh (float): IoU threshold for a RoI to be considered as a
        foreground.
    neg_iou_thresh_hi (float): RoI is considered to be the background
        if IoU is in
        [:obj:`neg_iou_thresh_hi`, :obj:`neg_iou_thresh_hi`).
    neg_iou_thresh_lo (float): See above.

"""

"""Assigns ground truth to sampled proposals.

This function samples total of :obj:`self.n_sample` RoIs
from the combination of :obj:`roi` and :obj:`bbox`.
The RoIs are assigned with the ground truth class labels as well as
bounding box offsets and scales to match the ground truth bounding
boxes. As many as :obj:`pos_ratio * self.n_sample` RoIs are
sampled as foregrounds.

Offsets and scales of bounding boxes are calculated using
:func:`model.utils.bbox_tools.bbox2loc`.
Also, types of input arrays and output arrays are same.

Here are notations.

* :math:`S` is the total number of sampled RoIs, which equals \
    :obj:`self.n_sample`.
* :math:`L` is number of object classes possibly including the \
    background.

Args:
    roi (array): Region of Interests (RoIs) from which we sample.
        Its shape is :math:`(R, 4)`
    bbox (array): The coordinates of ground truth bounding boxes.
        Its shape is :math:`(R', 4)`.
    label (array): Ground truth bounding box labels. Its shape
        is :math:`(R',)`. Its range is :math:`[0, L - 1]`, where
        :math:`L` is the number of foreground classes.
    loc_normalize_mean (tuple of four floats): Mean values to normalize
        coordinates of bouding boxes.
    loc_normalize_std (tupler of four floats): Standard deviation of
        the coordinates of bounding boxes.

Returns:
    (array, array, array):

    * **sample_roi**: Regions of interests that are sampled. \
        Its shape is :math:`(S, 4)`.
    * **gt_roi_loc**: Offsets and scales to match \
        the sampled RoIs to the ground truth bounding boxes. \
        Its shape is :math:`(S, 4)`.
    * **gt_roi_label**: Labels assigned to sampled RoIs. Its shape is \
        :math:`(S,)`. Its range is :math:`[0, L]`. The label with \
        value 0 is the background.

"""

"""Assign the ground truth bounding boxes to anchors.

Assigns the ground truth bounding boxes to anchors for training Region
Proposal Networks introduced in Faster R-CNN [#]_.

Offsets and scales to match anchors to the ground truth are
calculated using the encoding scheme of
:func:`model.utils.bbox_tools.bbox2loc`.

.. [#] Shaoqing Ren, Kaiming He, Ross Girshick, Jian Sun. \
Faster R-CNN: Towards Real-Time Object Detection with \
Region Proposal Networks. NIPS 2015.

Args:
    n_sample (int): The number of regions to produce.
    pos_iou_thresh (float): Anchors with IoU above this
        threshold will be assigned as positive.
    neg_iou_thresh (float): Anchors with IoU below this
        threshold will be assigned as negative.
    pos_ratio (float): Ratio of positive regions in the
        sampled regions.

"""

"""Assign ground truth supervision to sampled subset of anchors.

Types of input arrays and output arrays are same.

Here are notations.

* :math:`S` is the number of anchors.
* :math:`R` is the number of bounding boxes.

Args:
    bbox (array): Coordinates of bounding boxes. Its shape is
        :math:`(R, 4)`.
    anchor (array): Coordinates of anchors. Its shape is
        :math:`(S, 4)`.
    img_size (tuple of ints): A tuple :obj:`H, W`, which
        is a tuple of height and width of an image.

Returns:
    (array, array):

    #NOTE: it's scale not only  offset
    * **loc**: Offsets and scales to match the anchors to \
        the ground truth bounding boxes. Its shape is :math:`(S, 4)`.
    * **label**: Labels of anchors with values \
        :obj:`(1=positive, 0=negative, -1=ignore)`. Its shape \
        is :math:`(S,)`.

"""
